### PR TITLE
ISSUE 52: Replaced " : " with " _ " for writing and reading keys to the filesystem, as Windows does not allow " : "

### PR DESCRIPTION
**Pull request by IZEDx**

### CODE REVIEW

**Comment by rphillips** [comment]
We use this ```fingerprint:gsub("_", ":")``` two places... thinking we should write a function to sanitize the fingerprint

**Comment by rphillips** [comment]
nevermind. it's a different translation.

Thank you for the fix.

**Comment by creationix** [comment]
Looks good, but why rename keyPath and leave the old unused version.  It would be better to just edit keyPath directly.

**Comment by creationix** [comment]
https://github.com/luvit/lit/commit/2b4d9fb112bb8d9612dcedfe27fe5e6a83fc9e44

**Pull request closed without merging**
