### PR TITLE
Add options table to coro-http request

### PR DESCRIPTION
**Pull request by JohnnyMorganz**
*Continuation of https://github.com/luvit/lit/pull/230*

coro-http currently does not have the functionality to prevent following redirects.

This PR adds an `options` argument to the request function, which is a table of possible options for the request
This also replaces the `timeout` argument, which has now been moved into the `options` table, making it look like:
```
options
    timeout (number) - Default: nil
    followRedirects (boolean) - Default: true
```
This also allows more options to be added over time as required.

For backwards compatibility, if a `number` is provided instead of a table to the options parameter, it is assumed as the timeout.

### CODE REVIEW

**Review by squeek502 — APPROVED** [review]
Looks good, thanks for doing this.

**Comment by JohnnyMorganz** [comment]
Noticed a bug in how I handled if customOptions was a number, this should be fixed

**Comment by SinisterRectus** [comment]
Looks good to me. Can you bump package.version to 3.2.0?

**Comment by JohnnyMorganz** [comment]
Apologies for the delay again, bumped package.version

**Pull request merged**
